env:
    global:
        - CC_TEST_REPORTER_ID=f9e9b9a71d3f7f4917f96c3777022663b176523c581a7feb7dd10a4776c6f63d
language: php
php:
    - '5.6.39'
before_script:
    - mkdir -p build/logs/
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
    - composer update
    - vendor/bin/phpunit tests --coverage-text --coverage-clover build/logs/clover.xml
after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
    on_success: change
    on_failure: change
